### ISSUE TITLE
parou de funcionar

### ISSUE THREAD

**Issue by gumiranda** [franzon/react-native-pagarme-card-hash#2]
tava funcionando de boa, mas um dia a pagarme começou a retornar card_hash inválido.. mt estranho

**Comment by gumiranda** [comment]
migrei meu app pra expo e parou de gerar o card hash tbm

**Comment by franzon** [comment]
Opa, valeu por avisar. Assim que sobrar um tempo aqui vou ver o que está acontecendo.

**Comment by djalmaaraujo** [comment]
@franzon Boa tarde, se puder me dar norte posso ajudar a consertar. Estou precisando.

**Comment by franzon** [comment]
Estou investigando... Pensei que pudesse ser por causa de uma nova versão do `react-native-rsa-native`, mas fixei na versão anterior e não está funcionando.

**Comment by franzon** [comment]
Testei de novo e parece estar funcionando... Ainda está com erro?

**Comment by djalmaaraujo** [comment]
@franzon Alguma chance de funcionar com expo sem ejetar, etc?

**Comment by franzon** [comment]
Opa @djalmaaraujo .

Se o expo tiver suporte a criptografia RSA, aí daria pra implementar. Mas dei uma pesquisada rápida e não encontrei nada...

Estou pesquisando umas alternativas em JavaScript puro pra gerar o hash, aí em teoria funcionaria em qualquer lugar.
